<?php
require_once 'functions/acf-google-maps.php';
require_once 'functions/add-category-single-class.php';
// require_once 'functions/add-critical-style.php';
require_once 'functions/add-excerpt-read-more.php';
require_once 'functions/add-favicon.php';
require_once 'functions/add-google-analytics.php';
require_once 'functions/add-image-sizes.php';
require_once 'functions/add-livereload.php';
require_once 'functions/add-script.php';
require_once 'functions/add-style.php';
require_once 'functions/clear-cache-on-acf-save.php';
require_once 'functions/custom-nav-walker.php';
require_once 'functions/default-gallery-image.php';
require_once 'functions/disable-image-link.php';
require_once 'functions/disallow-robots-dev.php';
require_once 'functions/enable-post-thumbnail.php';
require_once 'functions/fancybox.php';
require_once 'functions/hide-admin-bar.php';
require_once 'functions/jquery.php';
require_once 'functions/modify-relative-image-url.php';
require_once 'functions/pagination.php';
require_once 'functions/post-header-image.php';
require_once 'functions/register-nav-menu.php';
require_once 'functions/remove-default-gallery-style.php';
require_once 'functions/remove-emojis.php';
require_once 'functions/remove-menus.php';
require_once 'functions/remove-more-anchor.php';
require_once 'functions/remove-rel-category.php';
require_once 'functions/remove-srcset.php';
require_once 'functions/remove-type-attribute.php';
require_once 'functions/remove-version-from-feed.php';
require_once 'functions/remove-wp-header-meta.php';
// require_once 'functions/add-acf-admin-page.php';
// require_once 'functions/add-comment-reply.php';
// require_once 'functions/add-rss-feeds-to-header.php';
// require_once 'functions/auto-update.php';
// require_once 'functions/cpt-archive-redirect.php';
require_once 'functions/custom-admin.php';
require_once 'functions/display-child-page.php';
require_once 'functions/register-widgets.php';
require_once 'functions/add-shortcode.php';
require_once 'functions/add-reviews.php';
require_once 'functions/add-text-separator.php';
// require_once 'functions/custom-editor-styles.php';
// require_once 'functions/custom-search-filter.php';
// require_once 'functions/disable-author-archive.php';
// require_once 'functions/disable-gutenberg-style.php';
// require_once 'functions/disable-plugin-notification.php';
// require_once 'functions/modify-excerpt-length.php';
// require_once 'functions/modify-menu.php';
// require_once 'functions/modify-query-post.php';
// require_once 'functions/pagination-extended.php';
// require_once 'functions/polylang.php';
// require_once 'functions/remove-comment-cookies.php';
// require_once 'functions/redirect-cf7.php';
